name: app_screen_login_kelomopk_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.4
  http: ^1.6.0  # Tambahkan ini
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # Tambahkan ini

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png" # Path ke gambar Anda
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # Ukuran ikon untuk windows